import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ReactQueryProvider } from "@/providers/react-query"
import { NuqsAdapter } from "nuqs/adapters/next/app"

const manrope = Manrope({
	variable: "--font-manrope",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br">
			<body
				className={`${manrope.variable} ${manrope.variable} antialiased`}
			>
				<ReactQueryProvider>
					<NuqsAdapter>{children}</NuqsAdapter>
					<Toaster position="top-center" richColors theme="light" />
				</ReactQueryProvider>
			</body>
		</html>
	);
}
